from rdflib import  URIRef 
from rdflib.namespace import DefinedNamespace, Namespace
class TSSO(DefinedNamespace):
  _NS = Namespace("https://w3id.org/tsso#")
  #START CLASSES ====
  #https://w3id.org/tsso#Outcome
  Outcome: URIRef  #see also ...

  #https://w3id.org/tsso#Driver
  Driver: URIRef  #see also ...

  #https://w3id.org/tsso#Provision
  Provision: URIRef  #see also ...

  #https://w3id.org/tsso#CounterMeasure
  CounterMeasure: URIRef  #see also ...

  #https://w3id.org/tsso#Capability
  Capability: URIRef  #see also ...

  #https://w3id.org/tsso#Threat
  Threat: URIRef  #see also ...

  #https://w3id.org/tsso#Concern
  Concern: URIRef  #see also ...

  #https://w3id.org/tsso#Problem
  Problem: URIRef  #see also ...

  #https://w3id.org/tsso#ComponentRequirement
  ComponentRequirement: URIRef  #see also ...

  #https://w3id.org/tsso#Component
  Component: URIRef  #see also ...

  #https://w3id.org/tsso#NISTSubCategory
  NISTSubCategory: URIRef  #see also ...

  #https://w3id.org/tsso#TechnicalCommittee
  TechnicalCommittee: URIRef  #see also ...

  #https://w3id.org/tsso#Organization
  Organization: URIRef  #see also ...

  #https://w3id.org/tsso#Connection
  Connection: URIRef  #see also ...

  #https://w3id.org/tsso#RiskAssesement
  RiskAssesement: URIRef  #see also ...

  #https://w3id.org/tsso#Asset
  Asset: URIRef  #see also ...

  #https://w3id.org/tsso#Risk
  Risk: URIRef  #see also ...

  #https://w3id.org/tsso#Vulnerability
  Vulnerability: URIRef  #see also ...

  #https://w3id.org/tsso#Framework
  Framework: URIRef  #see also ...

  #https://w3id.org/tsso#FrameworkElement
  FrameworkElement: URIRef  #see also ...

  #https://w3id.org/tsso#Publication
  Publication: URIRef  #see also ...

  #https://w3id.org/tsso#RequirementDependencyConstraint
  RequirementDependencyConstraint: URIRef  #see also ...

  #https://w3id.org/tsso#Architecture
  Architecture: URIRef  #see also ...

  #https://w3id.org/tsso#SolutionStructure
  SolutionStructure: URIRef  #see also ...

  #https://w3id.org/tsso#System
  System: URIRef  #see also ...

  #https://w3id.org/tsso#NISTFunction
  NISTFunction: URIRef  #see also ...

  #https://w3id.org/tsso#NISTCategory
  NISTCategory: URIRef  #see also ...

  #https://w3id.org/tsso#Configuration
  Configuration: URIRef  #see also ...

  #https://w3id.org/tsso#Constraint
  Constraint: URIRef  #see also ...

  #https://w3id.org/tsso#Device
  Device: URIRef  #see also ...

  #https://w3id.org/tsso#DevicePhysicalLimitation
  DevicePhysicalLimitation: URIRef  #see also ...

  #https://w3id.org/tsso#Domain
  Domain: URIRef  #see also ...

  #https://w3id.org/tsso#Firmware
  Firmware: URIRef  #see also ...

  #https://w3id.org/tsso#Function
  Function: URIRef  #see also ...

  #https://w3id.org/tsso#InputDevice
  InputDevice: URIRef  #see also ...

  #https://w3id.org/tsso#HUI
  HUI: URIRef  #see also ...

  #https://w3id.org/tsso#Interface
  Interface: URIRef  #see also ...

  #https://w3id.org/tsso#OperatingSystem
  OperatingSystem: URIRef  #see also ...

  #https://w3id.org/tsso#Policy
  Policy: URIRef  #see also ...

  #https://w3id.org/tsso#Profile
  Profile: URIRef  #see also ...

  #https://w3id.org/tsso#GenericProperty
  GenericProperty: URIRef  #see also ...

  #https://w3id.org/tsso#SystemRequirement
  SystemRequirement: URIRef  #see also ...

  #https://w3id.org/tsso#Status
  Status: URIRef  #see also ...

  #https://w3id.org/tsso#SupplementalGuidance
  SupplementalGuidance: URIRef  #see also ...

  #https://w3id.org/tsso#Tier
  Tier: URIRef  #see also ...

  #https://w3id.org/tsso#Tolerance
  Tolerance: URIRef  #see also ...

  #https://w3id.org/tsso#Type
  Type: URIRef  #see also ...

  #https://w3id.org/tsso#NonFunctionalRequirement
  NonFunctionalRequirement: URIRef  #see also ...

  #https://w3id.org/tsso#Stakeholder
  Stakeholder: URIRef  #see also ...

  #https://w3id.org/tsso#ComponentSolution
  ComponentSolution: URIRef  #see also ...

  #https://w3id.org/tsso#DeploymentNode
  DeploymentNode: URIRef  #see also ...

  #https://w3id.org/tsso#DeploymentSolution
  DeploymentSolution: URIRef  #see also ...

  #https://w3id.org/tsso#Port
  Port: URIRef  #see also ...

  #https://w3id.org/tsso#Service
  Service: URIRef  #see also ...

  #https://w3id.org/tsso#ReferenceArchitecture
  ReferenceArchitecture: URIRef  #see also ...

  #https://w3id.org/tsso#PublicationConstraint
  PublicationConstraint: URIRef  #see also ...

  #https://w3id.org/tsso#SWApplication
  SWApplication: URIRef  #see also ...

  #https://w3id.org/tsso#Supplier
  Supplier: URIRef  #see also ...

  #https://w3id.org/tsso#Protocol
  Protocol: URIRef  #see also ...

  #https://w3id.org/tsso#Algorithm
  Algorithm: URIRef  #see also ...

  #https://w3id.org/tsso#Channel
  Channel: URIRef  #see also ...

  #https://w3id.org/tsso#API
  API: URIRef  #see also ...

  #https://w3id.org/tsso#APIKind
  APIKind: URIRef  #see also ...

  #https://w3id.org/tsso#Kind
  Kind: URIRef  #see also ...

  #https://w3id.org/tsso#AccessControlMechanism
  AccessControlMechanism: URIRef  #see also ...

  #https://w3id.org/tsso#Mechanism
  Mechanism: URIRef  #see also ...

  #https://w3id.org/tsso#Actuator
  Actuator: URIRef  #see also ...

  #https://w3id.org/tsso#AuthenticationMechanism
  AuthenticationMechanism: URIRef  #see also ...

  #https://w3id.org/tsso#BooleanConstraint
  BooleanConstraint: URIRef  #see also ...

  #https://w3id.org/tsso#Buyer
  Buyer: URIRef  #see also ...

  #https://w3id.org/tsso#Functionality
  Functionality: URIRef  #see also ...

  #https://w3id.org/tsso#Category
  Category: URIRef  #see also ...

  #https://w3id.org/tsso#Requirement
  Requirement: URIRef  #see also ...

  #https://w3id.org/tsso#Composite
  Composite: URIRef  #see also ...

  #https://w3id.org/tsso#ConstrainedDevice
  ConstrainedDevice: URIRef  #see also ...

  #https://w3id.org/tsso#Core
  Core: URIRef  #see also ...

  #https://w3id.org/tsso#Customer
  Customer: URIRef  #see also ...

  #https://w3id.org/tsso#DetectionMechanism
  DetectionMechanism: URIRef  #see also ...

  #https://w3id.org/tsso#Developer
  Developer: URIRef  #see also ...

  #https://w3id.org/tsso#Product
  Product: URIRef  #see also ...

  #https://w3id.org/tsso#EmbeddedDevice
  EmbeddedDevice: URIRef  #see also ...

  #https://w3id.org/tsso#FunctionalRequirement
  FunctionalRequirement: URIRef  #see also ...

  #https://w3id.org/tsso#Guideline
  Guideline: URIRef  #see also ...

  #https://w3id.org/tsso#UI
  UI: URIRef  #see also ...

  #https://w3id.org/tsso#HWSolution
  HWSolution: URIRef  #see also ...

  #https://w3id.org/tsso#HostDevice
  HostDevice: URIRef  #see also ...

  #https://w3id.org/tsso#Manufacturer
  Manufacturer: URIRef  #see also ...

  #https://w3id.org/tsso#MemoryAccessControl
  MemoryAccessControl: URIRef  #see also ...

  #https://w3id.org/tsso#MobileDevice
  MobileDevice: URIRef  #see also ...

  #https://w3id.org/tsso#NetworkDevice
  NetworkDevice: URIRef  #see also ...

  #https://w3id.org/tsso#NetworkType
  NetworkType: URIRef  #see also ...

  #https://w3id.org/tsso#QualityAttribute
  QualityAttribute: URIRef  #see also ...

  #https://w3id.org/tsso#Practice
  Practice: URIRef  #see also ...

  #https://w3id.org/tsso#ProtocolProperty
  ProtocolProperty: URIRef  #see also ...

  #https://w3id.org/tsso#Recommendation
  Recommendation: URIRef  #see also ...

  #https://w3id.org/tsso#SWSolution
  SWSolution: URIRef  #see also ...

  #https://w3id.org/tsso#Scope
  Scope: URIRef  #see also ...

  #https://w3id.org/tsso#SecureBootMechanism
  SecureBootMechanism: URIRef  #see also ...

  #https://w3id.org/tsso#Sensor
  Sensor: URIRef  #see also ...

  #https://w3id.org/tsso#Standard
  Standard: URIRef  #see also ...

  #https://w3id.org/tsso#StorageMechanism
  StorageMechanism: URIRef  #see also ...

  #https://w3id.org/tsso#Technology
  Technology: URIRef  #see also ...

  #https://w3id.org/tsso#Tool
  Tool: URIRef  #see also ...

  #https://w3id.org/tsso#UpdateMechanism
  UpdateMechanism: URIRef  #see also ...

  #https://w3id.org/tsso#User
  User: URIRef  #see also ...

  #END CLASSES ====


  #START OBJECT PROPERTIES ====
  #https://w3id.org/tsso#achieves
  achieves: URIRef  #see also ...

  #https://w3id.org/tsso#promotedBy
  promotedBy: URIRef  #see also ...

  #https://w3id.org/tsso#addressedBy
  addressedBy: URIRef  #see also ...

  #https://w3id.org/tsso#addresses
  addresses: URIRef  #see also ...

  #https://w3id.org/tsso#addressesConcern
  addressesConcern: URIRef  #see also ...

  #https://w3id.org/tsso#affects
  affects: URIRef  #see also ...

  #https://w3id.org/tsso#isAffectedBy
  isAffectedBy: URIRef  #see also ...

  #https://w3id.org/tsso#applicableTo
  applicableTo: URIRef  #see also ...

  #https://w3id.org/tsso#applies
  applies: URIRef  #see also ...

  #https://w3id.org/tsso#associatedToSubCategory
  associatedToSubCategory: URIRef  #see also ...

  #https://w3id.org/tsso#considersProvision
  considersProvision: URIRef  #see also ...

  #https://w3id.org/tsso#belongsTo
  belongsTo: URIRef  #see also ...

  #https://w3id.org/tsso#ownerOf
  ownerOf: URIRef  #see also ...

  #https://w3id.org/tsso#channelUsedBy
  channelUsedBy: URIRef  #see also ...

  #https://w3id.org/tsso#usesChannel
  usesChannel: URIRef  #see also ...

  #https://w3id.org/tsso#composedOf
  composedOf: URIRef  #see also ...

  #https://w3id.org/tsso#composes
  composes: URIRef  #see also ...

  #https://w3id.org/tsso#configurationOf
  configurationOf: URIRef  #see also ...

  #https://w3id.org/tsso#hasConfiguration
  hasConfiguration: URIRef  #see also ...

  #https://w3id.org/tsso#connects
  connects: URIRef  #see also ...

  #https://w3id.org/tsso#connectsDestination
  connectsDestination: URIRef  #see also ...

  #https://w3id.org/tsso#isDestinationOf
  isDestinationOf: URIRef  #see also ...

  #https://w3id.org/tsso#connectsSource
  connectsSource: URIRef  #see also ...

  #https://w3id.org/tsso#isSourceOf
  isSourceOf: URIRef  #see also ...

  #https://w3id.org/tsso#considersAsset
  considersAsset: URIRef  #see also ...

  #https://w3id.org/tsso#considersRisk
  considersRisk: URIRef  #see also ...

  #https://w3id.org/tsso#considersThreat
  considersThreat: URIRef  #see also ...

  #https://w3id.org/tsso#considersVulnerability
  considersVulnerability: URIRef  #see also ...

  #https://w3id.org/tsso#consistOfFrameworkElement
  consistOfFrameworkElement: URIRef  #see also ...

  #https://w3id.org/tsso#containedBy
  containedBy: URIRef  #see also ...

  #https://w3id.org/tsso#contains
  contains: URIRef  #see also ...

  #https://w3id.org/tsso#demandsCapability
  demandsCapability: URIRef  #see also ...

  #https://w3id.org/tsso#dependsOn
  dependsOn: URIRef  #see also ...

  #https://w3id.org/tsso#describesSolution
  describesSolution: URIRef  #see also ...

  #https://w3id.org/tsso#solutionOfArchitecture
  solutionOfArchitecture: URIRef  #see also ...

  #https://w3id.org/tsso#developedBy
  developedBy: URIRef  #see also ...

  #https://w3id.org/tsso#develops
  develops: URIRef  #see also ...

  #https://w3id.org/tsso#enhancementOf
  enhancementOf: URIRef  #see also ...

  #https://w3id.org/tsso#hasEnhancement
  hasEnhancement: URIRef  #see also ...

  #https://w3id.org/tsso#exposedBy
  exposedBy: URIRef  #see also ...

  #https://w3id.org/tsso#exposes
  exposes: URIRef  #see also ...

  #https://w3id.org/tsso#handledBy
  handledBy: URIRef  #see also ...

  #https://w3id.org/tsso#handles
  handles: URIRef  #see also ...

  #https://w3id.org/tsso#hasArchitecture
  hasArchitecture: URIRef  #see also ...

  #https://w3id.org/tsso#hasCapability
  hasCapability: URIRef  #see also ...

  #https://w3id.org/tsso#hasCategory
  hasCategory: URIRef  #see also ...

  #https://w3id.org/tsso#hasConstraint
  hasConstraint: URIRef  #see also ...

  #https://w3id.org/tsso#hasDelegatedCapability
  hasDelegatedCapability: URIRef  #see also ...

  #https://w3id.org/tsso#isDelegatedCapabilityOf
  isDelegatedCapabilityOf: URIRef  #see also ...

  #https://w3id.org/tsso#hasDevicePhysicalLimitation
  hasDevicePhysicalLimitation: URIRef  #see also ...

  #https://w3id.org/tsso#isDevicePhysicalLimitationOf
  isDevicePhysicalLimitationOf: URIRef  #see also ...

  #https://w3id.org/tsso#hasDomain
  hasDomain: URIRef  #see also ...

  #https://w3id.org/tsso#isDomainOf
  isDomainOf: URIRef  #see also ...

  #https://w3id.org/tsso#hasFW
  hasFW: URIRef  #see also ...

  #https://w3id.org/tsso#hasFunction
  hasFunction: URIRef  #see also ...

  #https://w3id.org/tsso#hasHMI
  hasHMI: URIRef  #see also ...

  #https://w3id.org/tsso#hasInterface
  hasInterface: URIRef  #see also ...

  #https://w3id.org/tsso#hasLighterVersion
  hasLighterVersion: URIRef  #see also ...

  #https://w3id.org/tsso#hasMoreSecureVersion
  hasMoreSecureVersion: URIRef  #see also ...

  #https://w3id.org/tsso#hasMainCategory
  hasMainCategory: URIRef  #see also ...

  #https://w3id.org/tsso#hasSubCategory
  hasSubCategory: URIRef  #see also ...

  #https://w3id.org/tsso#hasMoreGeneralDomain
  hasMoreGeneralDomain: URIRef  #see also ...

  #https://w3id.org/tsso#hasMoreGeneralVersion
  hasMoreGeneralVersion: URIRef  #see also ...

  #https://w3id.org/tsso#hasSubDomain
  hasSubDomain: URIRef  #see also ...

  #https://w3id.org/tsso#hasMoreGeneralProblem
  hasMoreGeneralProblem: URIRef  #see also ...

  #https://w3id.org/tsso#hasSubProblem
  hasSubProblem: URIRef  #see also ...

  #https://w3id.org/tsso#hasSubVersion
  hasSubVersion: URIRef  #see also ...

  #https://w3id.org/tsso#hasOS
  hasOS: URIRef  #see also ...

  #https://w3id.org/tsso#hasPolicy
  hasPolicy: URIRef  #see also ...

  #https://w3id.org/tsso#hasPredecessor
  hasPredecessor: URIRef  #see also ...

  #https://w3id.org/tsso#hasSuccessor
  hasSuccessor: URIRef  #see also ...

  #https://w3id.org/tsso#hasProfile
  hasProfile: URIRef  #see also ...

  #https://w3id.org/tsso#hasProperty
  hasProperty: URIRef  #see also ...

  #https://w3id.org/tsso#hasRequirement
  hasRequirement: URIRef  #see also ...

  #https://w3id.org/tsso#hasScope
  hasScope: URIRef  #see also ...

  #https://w3id.org/tsso#hasSolutionStructure
  hasSolutionStructure: URIRef  #see also ...

  #https://w3id.org/tsso#hasStatus
  hasStatus: URIRef  #see also ...

  #https://w3id.org/tsso#hasSupplementalGuidance
  hasSupplementalGuidance: URIRef  #see also ...

  #https://w3id.org/tsso#isSupplementalGuidanceOf
  isSupplementalGuidanceOf: URIRef  #see also ...

  #https://w3id.org/tsso#hasTier
  hasTier: URIRef  #see also ...

  #https://w3id.org/tsso#hasTolerance
  hasTolerance: URIRef  #see also ...

  #https://w3id.org/tsso#hasType
  hasType: URIRef  #see also ...

  #https://w3id.org/tsso#improvesQA
  improvesQA: URIRef  #see also ...

  #https://w3id.org/tsso#interestedIn
  interestedIn: URIRef  #see also ...

  #https://w3id.org/tsso#isAssetOf
  isAssetOf: URIRef  #see also ...

  #https://w3id.org/tsso#ownsAsset
  ownsAsset: URIRef  #see also ...

  #https://w3id.org/tsso#manufactures
  manufactures: URIRef  #see also ...

  #https://w3id.org/tsso#partOfComponentSolution
  partOfComponentSolution: URIRef  #see also ...

  #https://w3id.org/tsso#partOfSolution
  partOfSolution: URIRef  #see also ...

  #https://w3id.org/tsso#partOfDeploymentSolution
  partOfDeploymentSolution: URIRef  #see also ...

  #https://w3id.org/tsso#solutionOf
  solutionOf: URIRef  #see also ...

  #https://w3id.org/tsso#protocolSupportedBy
  protocolSupportedBy: URIRef  #see also ...

  #https://w3id.org/tsso#supportsProtocol
  supportsProtocol: URIRef  #see also ...

  #https://w3id.org/tsso#protocolUsedBy
  protocolUsedBy: URIRef  #see also ...

  #https://w3id.org/tsso#usesProtocol
  usesProtocol: URIRef  #see also ...

  #https://w3id.org/tsso#providesFunction
  providesFunction: URIRef  #see also ...

  #https://w3id.org/tsso#providesFunctionality
  providesFunctionality: URIRef  #see also ...

  #https://w3id.org/tsso#providesService
  providesService: URIRef  #see also ...

  #https://w3id.org/tsso#serviceProvidedBy
  serviceProvidedBy: URIRef  #see also ...

  #https://w3id.org/tsso#published
  published: URIRef  #see also ...

  #https://w3id.org/tsso#publishedBy
  publishedBy: URIRef  #see also ...

  #https://w3id.org/tsso#referencesArchitecture
  referencesArchitecture: URIRef  #see also ...

  #https://w3id.org/tsso#refersTo
  refersTo: URIRef  #see also ...

  #https://w3id.org/tsso#relatedTo
  relatedTo: URIRef  #see also ...

  #https://w3id.org/tsso#relatedToProblem
  relatedToProblem: URIRef  #see also ...

  #https://w3id.org/tsso#requiresFunctionality
  requiresFunctionality: URIRef  #see also ...

  #https://w3id.org/tsso#requiresService
  requiresService: URIRef  #see also ...

  #https://w3id.org/tsso#serviceRequiredBy
  serviceRequiredBy: URIRef  #see also ...

  #https://w3id.org/tsso#runsOn
  runsOn: URIRef  #see also ...

  #https://w3id.org/tsso#serviceUsedBy
  serviceUsedBy: URIRef  #see also ...

  #https://w3id.org/tsso#suggestsCounterMeasure
  suggestsCounterMeasure: URIRef  #see also ...

  #https://w3id.org/tsso#supplies
  supplies: URIRef  #see also ...

  #https://w3id.org/tsso#uses
  uses: URIRef  #see also ...

  #https://w3id.org/tsso#usesAlgorithm
  usesAlgorithm: URIRef  #see also ...

  #https://w3id.org/tsso#usesEncryption
  usesEncryption: URIRef  #see also ...

  #https://w3id.org/tsso#vulnerableTo
  vulnerableTo: URIRef  #see also ...

  #END OBJECT PROPERTIES ====


  #START DATA PROPERTIES ====
  #https://w3id.org/tsso#appliesCryptography
  appliesCryptography: URIRef  #see also ...

  #https://w3id.org/tsso#dateOfAdoption
  dateOfAdoption: URIRef  #see also ...

  #https://w3id.org/tsso#dateOfPublication
  dateOfPublication: URIRef  #see also ...

  #https://w3id.org/tsso#dateOfWithdrawal
  dateOfWithdrawal: URIRef  #see also ...

  #https://w3id.org/tsso#isAuthenticated
  isAuthenticated: URIRef  #see also ...

  #https://w3id.org/tsso#isCritical
  isCritical: URIRef  #see also ...

  #https://w3id.org/tsso#isDebugInterface
  isDebugInterface: URIRef  #see also ...

  #https://w3id.org/tsso#isDisclosed
  isDisclosed: URIRef  #see also ...

  #https://w3id.org/tsso#isEmbedded
  isEmbedded: URIRef  #see also ...

  #https://w3id.org/tsso#isEncrypted
  isEncrypted: URIRef  #see also ...

  #https://w3id.org/tsso#isEssential
  isEssential: URIRef  #see also ...

  #https://w3id.org/tsso#isExternal
  isExternal: URIRef  #see also ...

  #https://w3id.org/tsso#isHard
  isHard: URIRef  #see also ...

  #https://w3id.org/tsso#isInternal
  isInternal: URIRef  #see also ...

  #https://w3id.org/tsso#isInternational
  isInternational: URIRef  #see also ...

  #https://w3id.org/tsso#isMandatory
  isMandatory: URIRef  #see also ...

  #https://w3id.org/tsso#isNormative
  isNormative: URIRef  #see also ...

  #https://w3id.org/tsso#isOnline
  isOnline: URIRef  #see also ...

  #https://w3id.org/tsso#isPhysical
  isPhysical: URIRef  #see also ...

  #https://w3id.org/tsso#isPublic
  isPublic: URIRef  #see also ...

  #https://w3id.org/tsso#isRealTime
  isRealTime: URIRef  #see also ...

  #https://w3id.org/tsso#isRemote
  isRemote: URIRef  #see also ...

  #https://w3id.org/tsso#isRoleProtected
  isRoleProtected: URIRef  #see also ...

  #https://w3id.org/tsso#isSW
  isSW: URIRef  #see also ...

  #https://w3id.org/tsso#isSmart
  isSmart: URIRef  #see also ...

  #https://w3id.org/tsso#isSolved
  isSolved: URIRef  #see also ...

  #https://w3id.org/tsso#isSpecialPurpose
  isSpecialPurpose: URIRef  #see also ...

  #https://w3id.org/tsso#isTransportable
  isTransportable: URIRef  #see also ...

  #https://w3id.org/tsso#isUpdatable
  isUpdatable: URIRef  #see also ...

  #https://w3id.org/tsso#isVulnerable
  isVulnerable: URIRef  #see also ...

  #https://w3id.org/tsso#isWireless
  isWireless: URIRef  #see also ...

  #https://w3id.org/tsso#pages
  pages: URIRef  #see also ...

  #https://w3id.org/tsso#priority
  priority: URIRef  #see also ...

  #https://w3id.org/tsso#probability
  probability: URIRef  #see also ...

  #https://w3id.org/tsso#receivesData
  receivesData: URIRef  #see also ...

  #https://w3id.org/tsso#securityLevel
  securityLevel: URIRef  #see also ...

  #https://w3id.org/tsso#sendsData
  sendsData: URIRef  #see also ...

  #https://w3id.org/tsso#severity
  severity: URIRef  #see also ...

  #https://w3id.org/tsso#size
  size: URIRef  #see also ...

  #END DATA PROPERTIES ====


  #START ANNOTATION PROPERTIES ====
  #https://w3id.org/tsso#abbr
  abbr: URIRef  #see also ...

  #https://w3id.org/tsso#replaceBy
  replaceBy: URIRef  #see also ...

  #END ANNOTATION PROPERTIES ====


